@tokeen=Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTczMzUyODEwNywicm9sIjoiVVNVQVJJT19FTElNSU5BUiJ9.Z3k-6kMVJN2nl3cresHpQ8hIY27YGKuzCukbl83G0J7Ei2Xu71Fw_9wX4HWxYdhJnGIGP9RsnL3cSyJdvBE7Lg
@type = application/json
@url = http://localhost:8080/api/career
###
GET {{url}}/findAll
Authorization:{{tokeen}}

###
POST {{url}}
Authorization:{{tokeen}}
Content-Type:{{type}}

{
  
   "name" : "",
   "type" : null,
   "capacity" : null,
   "location" : null
}
###
PUT {{url}}
Authorization:{{tokeen}}
Content-Type:{{type}}

{
  
   "name" : "",
   "type" : null,
   "capacity" : null,
   "location" : null
}

###
GET {{url}}/delete/2
Authorization:{{tokeen}}