@url= http://localhost:8080/api/role
@tokeen=Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTczNTcyMjM3Mywicm9sIjoiVVNVQVJJT19FTElNSU5BUiJ9.wc5wA6FmaiurLOThFGgQrQ_G0UCNJQFCSB2PZ9oEtW-LT-syCZbI-26alSA7Z4JNJX6NkqMK55VctUXehtyzNw


##
GET {{url}}/findAll
Authorization: {{tokeen}}
Content-Type: application/json

###
GET {{url}}/find/An
Authorization: {{tokeen}}
Content-Type: application/json

###
GET {{url}}/1
Authorization: {{tokeen}}
Content-Type: application/json

###
POST {{url}}
Authorization: {{tokeen}}
Content-Type: application/json

{
    "name" : "Ander123",
    "password" : "holaa",
    "username" : "anderk222"
}